# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "install"
      workingDir: "."

  - task: Npm@1
    displayName: "npm build"
    inputs:
      command: "custom"
      workingDir: "."
      customCommand: "run-script build-token"

  - task: CopyFiles@2
    displayName: "copy build to staging area"
    inputs:
      SourceFolder: "dist"
      Contents: "**"
      TargetFolder: "$(build.artifactstagingdirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "publish artifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "frontend"
      publishLocation: "Container"
