export const ANSWERS_LIST_LOAD = "ANSWERS_LIST_LOAD";
export const ANSWERS_LIST_LOADED = "ANSWERS_LIST_LOADED";
export const ANSWERS_LIST_ERROR = "ANSWERS_LIST_ERROR";
export const ANSWERS_DETAIL_LOAD = "ANSWERS_DETAIL_LOAD";
export const ANSWERS_DETAIL_LOADED = "ANSWERS_DETAIL_LOADED";
export const ANSWERS_DETAIL_ERROR = "ANSWERS_DETAIL_ERROR";
